ServerTokens Prod
ServerSignature Off

RemoteIPHeader X-Forwarded-For
SetEnvIf X-Forwarded-Proto "https" HTTPS=on

<Directory /var/www/droptaxi/public>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

